# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xci
# IP: The module: 'Division_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xci
# IP: The module: 'Division_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
