# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xci
# IP: The module: 'FloatingPointDivision_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FloatingPointDivision_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xci
# IP: The module: 'FloatingPointDivision_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FloatingPointDivision_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
