# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZYBOFloatingPointDivision.xdc

# Block Designs: bd/FloatingPointDivision/FloatingPointDivision.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision || ORIG_REF_NAME==FloatingPointDivision} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_0_0/FloatingPointDivision_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_floating_point_0_0 || ORIG_REF_NAME==FloatingPointDivision_floating_point_0_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_1_0/FloatingPointDivision_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_floating_point_1_0 || ORIG_REF_NAME==FloatingPointDivision_floating_point_1_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_2_0/FloatingPointDivision_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_floating_point_2_0 || ORIG_REF_NAME==FloatingPointDivision_floating_point_2_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_0_0/FloatingPointDivision_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_axi_gpio_0_0 || ORIG_REF_NAME==FloatingPointDivision_axi_gpio_0_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_1_0/FloatingPointDivision_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_axi_gpio_1_0 || ORIG_REF_NAME==FloatingPointDivision_axi_gpio_1_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_2_0/FloatingPointDivision_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_axi_gpio_2_0 || ORIG_REF_NAME==FloatingPointDivision_axi_gpio_2_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_processing_system7_0_1 || ORIG_REF_NAME==FloatingPointDivision_processing_system7_0_1} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_xbar_0/FloatingPointDivision_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_xbar_0 || ORIG_REF_NAME==FloatingPointDivision_xbar_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_ps7_0_axi_periph_0/FloatingPointDivision_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_ps7_0_axi_periph_0 || ORIG_REF_NAME==FloatingPointDivision_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_rst_ps7_0_50M_0/FloatingPointDivision_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_rst_ps7_0_50M_0 || ORIG_REF_NAME==FloatingPointDivision_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FloatingPointDivision_auto_pc_0 || ORIG_REF_NAME==FloatingPointDivision_auto_pc_0} -quiet] -quiet

# XDC: bd/FloatingPointDivision/FloatingPointDivision_ooc.xdc
