# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.cache/wt [current_project]
set_property parent.project_path C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/OAkun/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/hdl/FloatingPointDivision_wrapper.v
add_files C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/FloatingPointDivision.bd
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_0_0/FloatingPointDivision_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_1_0/FloatingPointDivision_floating_point_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_floating_point_2_0/FloatingPointDivision_floating_point_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_0_0/FloatingPointDivision_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_0_0/FloatingPointDivision_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_0_0/FloatingPointDivision_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_1_0/FloatingPointDivision_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_1_0/FloatingPointDivision_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_1_0/FloatingPointDivision_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_2_0/FloatingPointDivision_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_2_0/FloatingPointDivision_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_axi_gpio_2_0/FloatingPointDivision_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_processing_system7_0_1/FloatingPointDivision_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_xbar_0/FloatingPointDivision_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_rst_ps7_0_50M_0/FloatingPointDivision_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_rst_ps7_0_50M_0/FloatingPointDivision_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_rst_ps7_0_50M_0/FloatingPointDivision_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/FloatingPointDivision_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/constrs_1/new/ZYBOFloatingPointDivision.xdc
set_property used_in_implementation false [get_files C:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/constrs_1/new/ZYBOFloatingPointDivision.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FloatingPointDivision_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FloatingPointDivision_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FloatingPointDivision_wrapper_utilization_synth.rpt -pb FloatingPointDivision_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
