# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2.xci
# IP: The module: 'Division_mdm_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_mdm_1_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2.xci
# IP: The module: 'Division_mdm_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_2/Division_mdm_1_2_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'Division_mdm_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
