# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources_1/Nexys4DDRMaster.xdc

# Block Designs: bd/Division/Division.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division || ORIG_REF_NAME==Division} -quiet] -quiet

# IP: bd/Division/ip/Division_floating_point_0_1/Division_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_floating_point_0_1 || ORIG_REF_NAME==Division_floating_point_0_1} -quiet] -quiet

# IP: bd/Division/ip/Division_DivisionTop_0_1/Division_DivisionTop_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_DivisionTop_0_1 || ORIG_REF_NAME==Division_DivisionTop_0_1} -quiet] -quiet

# IP: bd/Division/ip/Division_floating_point_1_0/Division_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_floating_point_1_0 || ORIG_REF_NAME==Division_floating_point_1_0} -quiet] -quiet

# IP: bd/Division/ip/Division_floating_point_2_0/Division_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_floating_point_2_0 || ORIG_REF_NAME==Division_floating_point_2_0} -quiet] -quiet

# XDC: bd/Division/Division_ooc.xdc
