# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0.xci
# IP: The module: 'FloatingPointDivision_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FloatingPointDivision_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0.xci
# IP: The module: 'FloatingPointDivision_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/FloatingDivisionZybo/FloatingDivisionZybo.srcs/sources_1/bd/FloatingPointDivision/ip/FloatingPointDivision_auto_pc_0/FloatingPointDivision_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FloatingPointDivision_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
