# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/OAkun/Division/Division.cache/wt [current_project]
set_property parent.project_path C:/Users/OAkun/Division/Division.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/OAkun/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/OAkun/Division/Division.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/hdl/Division_wrapper.v
add_files C:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/Division.bd
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_floating_point_0_2/Division_floating_point_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_microblaze_0_0/Division_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_microblaze_0_0/Division_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_microblaze_0_0/Division_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_0_0/Division_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_0_0/Division_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_0_0/Division_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_2_0/Division_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_2_0/Division_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_gpio_2_0/Division_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_uartlite_0_0/Division_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_uartlite_0_0/Division_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_axi_uartlite_0_0/Division_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_clk_wiz_0_0/Division_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_clk_wiz_0_0/Division_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_clk_wiz_0_0/Division_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_dlmb_v10_1/Division_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_dlmb_v10_1/Division_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_ilmb_v10_1/Division_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_ilmb_v10_1/Division_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_dlmb_bram_if_cntlr_1/Division_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_ilmb_bram_if_cntlr_1/Division_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_lmb_bram_1/Division_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_1/Division_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_mdm_1_1/Division_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_rst_clk_wiz_0_100M_0/Division_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_rst_clk_wiz_0_100M_0/Division_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_rst_clk_wiz_0_100M_0/Division_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_xbar_0/Division_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/Division_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/OAkun/Division/Division.srcs/sources_1/bd/Division/ip/Division_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/OAkun/Division/Division.srcs/constrs_1/imports/sources_1/Nexys4DDRMaster.xdc
set_property used_in_implementation false [get_files C:/Users/OAkun/Division/Division.srcs/constrs_1/imports/sources_1/Nexys4DDRMaster.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Division_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Division_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Division_wrapper_utilization_synth.rpt -pb Division_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
