# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources_1/Nexys4DDRMaster.xdc

# Block Designs: bd/Division/Division.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division || ORIG_REF_NAME==Division} -quiet] -quiet

# IP: bd/Division/ip/Division_DivisionTop_0_1/Division_DivisionTop_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_DivisionTop_0_1 || ORIG_REF_NAME==Division_DivisionTop_0_1} -quiet] -quiet

# IP: bd/Division/ip/Division_floating_point_0_2/Division_floating_point_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_floating_point_0_2 || ORIG_REF_NAME==Division_floating_point_0_2} -quiet] -quiet

# IP: bd/Division/ip/Division_microblaze_0_0/Division_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_microblaze_0_0 || ORIG_REF_NAME==Division_microblaze_0_0} -quiet] -quiet

# IP: bd/Division/ip/Division_axi_gpio_0_0/Division_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_axi_gpio_0_0 || ORIG_REF_NAME==Division_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Division/ip/Division_axi_gpio_1_0/Division_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_axi_gpio_1_0 || ORIG_REF_NAME==Division_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Division/ip/Division_axi_gpio_2_0/Division_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_axi_gpio_2_0 || ORIG_REF_NAME==Division_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Division/ip/Division_axi_uartlite_0_0/Division_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_axi_uartlite_0_0 || ORIG_REF_NAME==Division_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Division/ip/Division_clk_wiz_0_0/Division_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_clk_wiz_0_0 || ORIG_REF_NAME==Division_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Division/ip/Division_dlmb_v10_1/Division_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_dlmb_v10_1 || ORIG_REF_NAME==Division_dlmb_v10_1} -quiet] -quiet

# IP: bd/Division/ip/Division_ilmb_v10_1/Division_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_ilmb_v10_1 || ORIG_REF_NAME==Division_ilmb_v10_1} -quiet] -quiet

# IP: bd/Division/ip/Division_dlmb_bram_if_cntlr_1/Division_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Division_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Division/ip/Division_ilmb_bram_if_cntlr_1/Division_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Division_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Division/ip/Division_lmb_bram_1/Division_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_lmb_bram_1 || ORIG_REF_NAME==Division_lmb_bram_1} -quiet] -quiet

# IP: bd/Division/ip/Division_mdm_1_1/Division_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_mdm_1_1 || ORIG_REF_NAME==Division_mdm_1_1} -quiet] -quiet

# IP: bd/Division/ip/Division_rst_clk_wiz_0_100M_0/Division_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Division_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Division/ip/Division_xbar_0/Division_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_xbar_0 || ORIG_REF_NAME==Division_xbar_0} -quiet] -quiet

# IP: bd/Division/ip/Division_microblaze_0_axi_periph_1/Division_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_microblaze_0_axi_periph_1 || ORIG_REF_NAME==Division_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/Division/ip/Division_util_vector_logic_0_0/Division_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Division_util_vector_logic_0_0 || ORIG_REF_NAME==Division_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/Division/Division_ooc.xdc
